import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {map, share, shareReplay} from 'rxjs/operators';

@Injectable({
  providedIn: 'root',
})
export class PostsService {
  posts$ = this.http.get<Post[]>('http://localhost:8200/posts').pipe(shareReplay(1));

  getPost(id:number) {
    return this.posts$.pipe(map((posts) => posts.find((post) => post.id === id)));
  }

  constructor(private http: HttpClient) {}
}

// Generated by https://quicktype.io

export interface Post {
  userId: number;
  id: number;
  title: string;
  body: string;
}
